teachers:
  - id: 1
    name: "Xu Yingguo"         # G10 Chinese
  - id: 2
    name: "Liu Weiyun"         # G11 Chinese
  - id: 3
    name: "Qu Xiaoyu"          # G12 Chinese
  - id: 4
    name: "Jessica"            # Chemistry / AS Chem
  - id: 5
    name: "Huang Tongyun"      # AS Physics
  - id: 6
    name: "Yunfei"             # IG Math, AP Stat, Further Math
  - id: 7
    name: "Feng Yuanyuan"      # Art
  - id: 8
    name: "Serena"             # IG Biology
  - id: 9
    name: "William"            # IG Economics / AP Economics
  - id: 10
    name: "Carol"              # English
  - id: 11
    name: "Jenny"              # EL / Debate / West‑Culture
  - id: 12
    name: "Zora"               # IELTS
  - id: 13
    name: "Dawn"               # AS Math
  - id: 14
    name: "Randy"              # Literature & Culture
  - id: 15
    name: "Chen Gaili"         # World History (Bil.)
  - id: 16
    name: "Wang Jing"          # World Geography (Bil.)
  - id: 17
    name: "Liang Qingzhu"      # Physics (General)
  - id: 18
    name: "Kou Jinlong"        # PE
  - id: 19
    name: "Pedro Maia"         # FT PE


students:
  # ---------- Grade 10  (Homeroom teacher ID 9 – William) ----------
  - id: 1
    homeroom_teacher: 9
    name: "Rita Huang"
    grade: 10
  - id: 2
    homeroom_teacher: 9
    name: "Candy Lang"
    grade: 10
  - id: 3
    homeroom_teacher: 9
    name: "Mia Li"
    grade: 10
  - id: 4
    homeroom_teacher: 9
    name: "Akila Wei"
    grade: 10
  - id: 5
    homeroom_teacher: 9
    name: "Cindy Wei"
    grade: 10
  - id: 6
    homeroom_teacher: 9
    name: "Wendy Wu"
    grade: 10
  - id: 7
    homeroom_teacher: 9
    name: "Kevin Zhang"
    grade: 10
  - id: 8
    homeroom_teacher: 9
    name: "Chris Tang"
    grade: 10
  - id: 9
    homeroom_teacher: 9
    name: "Russel Zhao"
    grade: 10
  - id: 10
    homeroom_teacher: 9
    name: "Jordan Zhao"
    grade: 10
  - id: 11
    homeroom_teacher: 9
    name: "Jason Zhao"
    grade: 10
  - id: 12
    homeroom_teacher: 9
    name: "Hama Jia"
    grade: 10
  - id: 13
    homeroom_teacher: 9
    name: "Franky Fang"
    grade: 10

  # ---------- Grade 11  (Homeroom teacher ID 13 – Dawn) ----------
  - id: 14
    homeroom_teacher: 13
    name: "Sherry Chen"
    grade: 11
  - id: 15
    homeroom_teacher: 13
    name: "Helen Han"
    grade: 11
  - id: 16
    homeroom_teacher: 13
    name: "Camellia Ma"
    grade: 11
  - id: 17
    homeroom_teacher: 13
    name: "Betty Wang"
    grade: 11
  - id: 18
    homeroom_teacher: 13
    name: "Jenny Yang"
    grade: 11
  - id: 19
    homeroom_teacher: 13
    name: "Peter Dong"
    grade: 11
  - id: 20
    homeroom_teacher: 13
    name: "Luke Li"
    grade: 11

  # ---------- Grade 12  (Homeroom teacher ID 4 – Jessica) ----------
  - id: 21
    homeroom_teacher: 4
    name: "Sharon Tian"
    grade: 12
  - id: 22
    homeroom_teacher: 4
    name: "Tony Liu"
    grade: 12
  - id: 23
    homeroom_teacher: 4
    name: "Henry Li"
    grade: 12
  - id: 24
    homeroom_teacher: 4
    name: "Steven Yang"
    grade: 12
  - id: 25
    homeroom_teacher: 4
    name: "Eason Zhu"
    grade: 12

# ----------  COURSES  ----------
courses:
  - id: 1
    name: "Chinese (G10)"
    teacher_id: 1
  - id: 2
    name: "Chinese (G11)"
    teacher_id: 2
  - id: 3
    name: "Chinese (G12)"
    teacher_id: 3
  - id: 4
    name: "AS Chemistry"
    teacher_id: 4
  - id: 5
    name: "Chemistry"
    teacher_id: 4
  - id: 6
    name: "AS Physics"
    teacher_id: 5
  - id: 7
    name: "Physics"
    teacher_id: 17        # now taught by Liang Qingzhu
  - id: 8
    name: "IG Math"
    teacher_id: 6
  - id: 9
    name: "Further Math"
    teacher_id: 6
  - id: 10
    name: "AP Statistics"
    teacher_id: 6
  - id: 11
    name: "AS Math"
    teacher_id: 13
  - id: 12
    name: "IG Biology"
    teacher_id: 8
  - id: 13
    name: "IG Economics"
    teacher_id: 9
  - id: 14
    name: "AP Economics"
    teacher_id: 9
  - id: 15
    name: "Art"
    teacher_id: 7
  - id: 16
    name: "English"
    teacher_id: 10
  - id: 17
    name: "IELTS"
    teacher_id: 12
  - id: 18
    name: "EL (Extensive Reading)"
    teacher_id: 11
  - id: 19
    name: "Debate"
    teacher_id: 11
  - id: 20
    name: "Western Culture"
    teacher_id: 11
  - id: 21
    name: "Literature & Culture"
    teacher_id: 14
  - id: 22
    name: "British History"
    teacher_id: 15
  - id: 23
    name: "World Geography (Bil.)"
    teacher_id: 16
  - id: 24
    name: "PE"
    teacher_id: 18        # now taught by Kou Jinlong
  - id: 25
    name: "FT PE"
    teacher_id: 19        # now taught by Pedro Maia
  - id: 26
    name: "SAT Prep"
    teacher_id: 11

course_requirements:
  10:
    - course_id: 12   # IG Biology
      periods_per_week: 6
    - course_id: 13   # IG Economics
      periods_per_week: 6
    - course_id: 8    # IG Math
      periods_per_week: 5
    - course_id: 5    # Chemistry
      periods_per_week: 5
    - course_id: 7    # Physics
      periods_per_week: 5
    - course_id: 1    # Chinese (G10)
      periods_per_week: 1
    - course_id: 16   # English
      periods_per_week: 3
    - course_id: 17   # IELTS
      periods_per_week: 3
    - course_id: 15   # Art
      periods_per_week: 6
    - course_id: 24   # PE
      periods_per_week: 3
    - course_id: 25   # FT PE
      periods_per_week: 1
    - course_id: 22   # US/World History (bil.)
      periods_per_week: 1
  11:
    - course_id: 4    # AS Chemistry
      periods_per_week: 9
    - course_id: 6    # AS Physics
      periods_per_week: 7
    - course_id: 9    # Further Math
      periods_per_week: 9
    - course_id: 13   # IG Economics
      periods_per_week: 2
    - course_id: 15   # Art
      periods_per_week: 7
    - course_id: 2    # Chinese (G11)
      periods_per_week: 4
    - course_id: 17   # IELTS
      periods_per_week: 2
    - course_id: 24   # PE
      periods_per_week: 3
    - course_id: 22   # British History
      periods_per_week: 1
    - course_id: 23   # World Geography (Bil.)
      periods_per_week: 1
    - course_id: 25   # FT PE
      periods_per_week: 1
    - course_id: 11   # AS Math
      periods_per_week: 6
  12:
    - course_id: 10   # AP Statistics
      periods_per_week: 6
    - course_id: 6    # AP Physics
      periods_per_week: 3
    - course_id: 14   # AP Economics
      periods_per_week: 3
    - course_id: 3    # Chinese (G12)
      periods_per_week: 1
    - course_id: 15   # Art
      periods_per_week: 2
    - course_id: 24   # PE
      periods_per_week: 3
    - course_id: 18   # EL
      periods_per_week: 2
    - course_id: 19   # Debate
      periods_per_week: 3
    - course_id: 20   # Western Culture
      periods_per_week: 1
    - course_id: 21   # Literature & Culture
      periods_per_week: 5
    - course_id: 26   # SAT Prep
      periods_per_week: 2
    - course_id: 25   # FT PE
      periods_per_week: 1

# ----------  FIXED EVENTS  ----------
# (Currently none – Friday 7th‑period Art for all grades is already baked into requirements.)
fixed_events: []

# ----------  TEACHER CONSTRAINTS  ----------
# No extra “can’t‑teach” slots needed: school day ends after period 7 on Friday.
teacher_constraints: {}

# ----------  TEACHING LOAD LIMITS  ----------
teacher_limits:
  1: 24
  2: 24
  3: 24
  4: 24
  5: 24
  6: 24
  7: 24
  8: 24
  9: 24
  10: 24
  11: 24
  12: 24
  13: 24
  14: 24
  15: 24
  16: 24
  17: 24
