classes:
  G10:
    courses:
      - course_id: 1  # Chinese
        periods_per_week: 5
      - course_id: 4  # IG Math
        periods_per_week: 4
      - course_id: 3  # AP Physics
        periods_per_week: 3
  G11:
    courses:
      - course_id: 2  # AS Chemistry
        periods_per_week: 4
      - course_id: 7  # AP Statistics
        periods_per_week: 3
      - course_id: 8  # IG Biology
        periods_per_week: 5
  G12:
    courses:
      - course_id: 5  # Art
        periods_per_week: 2
      - course_id: 6  # Chemistry
        periods_per_week: 4
      - course_id: 1  # Chinese
        periods_per_week: 5

fixed_events:
  # - day: Monday
  #   period: 2
  #   course: "Flag-Raising"
  # - day: Monday
  #   period: 3
  #   course: "Flag-Raising"

# Now teacher_constraints are positive assertions:
teacher_constraints:
  "Mr. Huang":
    - day: Friday
      period: 9
      class: G10
      course: "AP Physics"
  Yunfei:
    - day: Monday
      period: 9
      class: G11
      course: "IG Math"

teacher_limits:
  "Mr. Huang": 15
  Yunfei: 15
  Dawn: 15
  Jessica: 15
  Serena: 15
  Yuanyuan: 15
  Yingguo: 15

courses:
  - id: 1
    name: Chinese
    teachers:
      - Yingguo
  - id: 2
    name: AS Chemistry
    teachers:
      - Jessica
  - id: 3
    name: AP Physics
    teachers:
      - "Mr. Huang"
  - id: 4
    name: IG Math
    teachers:
      - Yunfei
      - Dawn
  - id: 5
    name: Art
    teachers:
      - Yuanyuan
  - id: 6
    name: Chemistry
    teachers:
      - Jessica
  - id: 7
    name: AP Statistics
    teachers:
      - Yunfei
      - Dawn
  - id: 8
    name: IG Biology
    teachers:
      - Serena

cotaught: []
