teachers:
  - id: 1
    name: "Yingguo"
  - id: 2
    name: "Jessica"
  - id: 3
    name: "Mr. Huang"
  - id: 4
    name: "Yunfei"
  - id: 5
    name: "Yuanyuan"
  - id: 6
    name: "Serena"
  - id: 7
    name: "Ricardo"
  - id: 8
    name: "Maia"
  - id: 9
    name: "Med"
  - id: 10
    name: "Carol"
  - id: 11
    name: "Mr. Kou"

courses:
  - id: 1
    name: "Chinese"
    teacher_id: 1
  - id: 2
    name: "AS Chemistry"
    teacher_id: 2
  - id: 3
    name: "AP Physics"
    teacher_id: 3
  - id: 4
    name: "IG Math"
    teacher_id: 4
  - id: 5
    name: "Art"
    teacher_id: 5
  - id: 6
    name: "Chemistry"
    teacher_id: 2
  - id: 7
    name: "AP Statistics"
    teacher_id: 4
  - id: 8
    name: "IG Biology"
    teacher_id: 6
  - id: 9
    name: "FT PE"
    teacher_id: 7
  - id: 10
    name: "IELTS"
    teacher_id: 9
  - id: 11
    name: "English"
    teacher_id: 10
  - id: 12
    name: "US History"
    teacher_id: 9
  - id: 13
    name: "PE"
    teacher_id: 11
  - id: 14
    name: "Physics"
    teacher_id: 3

classes:
  G10:
    courses:
      - course_id: 8  # IG Biology
        periods_per_week: 6
      - course_id: 1  # Chinese
        periods_per_week: 1
      - course_id: 4  # IG Math
        periods_per_week: 6
      - course_id: 6  # Chemistry
        periods_per_week: 4
      - course_id: 9  # FT PE
        periods_per_week: 1
      - course_id: 10  # IELTS
        periods_per_week: 3
      - course_id: 11  # English
        periods_per_week: 5
      - course_id: 12  # US History
        periods_per_week: 1
      - course_id: 5   # Art
        periods_per_week: 6
      - course_id: 13
        periods_per_week: 3
      - course_id: 3
        periods_per_week: 3
      - course_id: 14
        periods_per_week: 6
  G11:
    courses:
      - course_id: 2  # AS Chemistry
        periods_per_week: 4
      - course_id: 7  # AP Statistics
        periods_per_week: 3
  G12:
    courses:
      - course_id: 5  # Art
        periods_per_week: 2
      - course_id: 6  # Chemistry
        periods_per_week: 4
      - course_id: 1  # Chinese
        periods_per_week: 5

fixed_events: []

teacher_constraints:
  3:
    - day: Friday
      period: 9
      class: G10
      course: 3
  4:
    - day: Monday
      period: 9
      class: G11
      course: 4

teacher_limits:
  1: 15
  2: 15
  3: 15
  4: 15
  5: 15
  6: 15
  7: 15
  8: 15
  9: 15
  10: 15
  11: 15

cotaught: []